# Generated by Django 6.0.7 on 2026-07-23 04:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_pembayaran', models.CharField(editable=False, max_length=30, unique=True)),
                ('metode_pembayaran', models.CharField(choices=[('transfer_bank', 'Transfer Bank'), ('qris', 'QRIS'), ('tunai', 'Tunai')], default='transfer_bank', max_length=30)),
                ('jumlah_pembayaran', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('bukti_pembayaran', models.ImageField(blank=True, null=True, upload_to='pembayaran/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('nama_pengirim', models.CharField(blank=True, max_length=150)),
                ('bank_pengirim', models.CharField(blank=True, max_length=100)),
                ('status_pembayaran', models.CharField(choices=[('menunggu_pembayaran', 'Menunggu Pembayaran'), ('menunggu_verifikasi', 'Menunggu Verifikasi'), ('ditolak', 'Pembayaran Ditolak'), ('diterima', 'Pembayaran Diterima')], default='menunggu_pembayaran', max_length=30)),
                ('tanggal_upload', models.DateTimeField(blank=True, null=True)),
                ('tanggal_verifikasi', models.DateTimeField(blank=True, null=True)),
                ('alasan_penolakan', models.TextField(blank=True)),
                ('catatan_petugas', models.TextField(blank=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_pendaftaran', models.CharField(editable=False, max_length=30, unique=True)),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('nomor_hp', models.CharField(max_length=20)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('ukuran_kaos', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=2)),
                ('nama_kontak_darurat', models.CharField(max_length=150)),
                ('nomor_kontak_darurat', models.CharField(max_length=20)),
                ('riwayat_penyakit', models.TextField(blank=True, help_text='Opsional. Kosongkan jika tidak ada.')),
                ('harga_tiket', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status_pendaftaran', models.CharField(choices=[('belum_dikonfirmasi', 'Belum Dikonfirmasi'), ('dikonfirmasi', 'Dikonfirmasi'), ('check_in', 'Check In'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='belum_dikonfirmasi', max_length=30)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('waktu_pendaftaran', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('catatan', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Pendaftaran',
                'verbose_name_plural': 'Pendaftaran',
                'ordering': ['-waktu_pendaftaran'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('nomor_hp', models.CharField(max_length=20)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('alamat', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profil/customer/')),
                ('aktif', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customer',
                'ordering': ['nama_lengkap'],
            },
        ),
    ]
