# Generated by Django 6.0.7 on 2026-07-23 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0001_initial'),
        ('customer', '0001_initial'),
        ('petugas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran',
            name='diverifikasi_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembayaran_diverifikasi', to='petugas.petugas'),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pendaftaran', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pendaftaran', to='administrator.event'),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='kategori_tiket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pendaftaran', to='administrator.kategoritiket'),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='pendaftaran',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='customer.pendaftaran'),
        ),
        migrations.AddIndex(
            model_name='pendaftaran',
            index=models.Index(fields=['kode_pendaftaran'], name='customer_pe_kode_pe_2c67ac_idx'),
        ),
        migrations.AddIndex(
            model_name='pendaftaran',
            index=models.Index(fields=['status_pendaftaran'], name='customer_pe_status__762d90_idx'),
        ),
        migrations.AddIndex(
            model_name='pendaftaran',
            index=models.Index(fields=['event'], name='customer_pe_event_i_fea073_idx'),
        ),
        migrations.AddIndex(
            model_name='pembayaran',
            index=models.Index(fields=['status_pembayaran'], name='customer_pe_status__335993_idx'),
        ),
        migrations.AddIndex(
            model_name='pembayaran',
            index=models.Index(fields=['kode_pembayaran'], name='customer_pe_kode_pe_725fd5_idx'),
        ),
    ]
