# Generated by Django 5.2.16 on 2026-07-24 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_kode_checkin_dan_validasi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendaftaran',
            name='nama_kontak_darurat',
        ),
        migrations.RemoveField(
            model_name='pendaftaran',
            name='nomor_kontak_darurat',
        ),
        migrations.RemoveField(
            model_name='pendaftaran',
            name='riwayat_penyakit',
        ),
    ]
