# Generated by Django 6.0.7 on 2026-07-23 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_petugas', models.CharField(max_length=20, unique=True)),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('nomor_hp', models.CharField(max_length=20)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('alamat', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profil/petugas/')),
                ('aktif', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='petugas_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Petugas',
                'verbose_name_plural': 'Petugas',
                'ordering': ['nama_lengkap'],
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_check_in', models.DateTimeField(auto_now_add=True)),
                ('metode', models.CharField(choices=[('qr_code', 'Scan QR Code'), ('manual', 'Input Manual')], default='qr_code', max_length=20)),
                ('kode_qr_dipindai', models.CharField(blank=True, max_length=100)),
                ('catatan', models.TextField(blank=True)),
                ('pendaftaran', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_in', to='customer.pendaftaran')),
                ('petugas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riwayat_check_in', to='petugas.petugas')),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-in',
                'ordering': ['-waktu_check_in'],
            },
        ),
    ]
