# Generated by Django 6.0.7 on 2026-07-23 04:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('nomor_hp', models.CharField(blank=True, max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profil/administrator/')),
                ('aktif', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrator',
                'verbose_name_plural': 'Administrator',
                'ordering': ['nama_lengkap'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_event', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('poster_event', models.ImageField(blank=True, null=True, upload_to='event/poster/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('banner_event', models.ImageField(blank=True, null=True, upload_to='event/banner/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('deskripsi', models.TextField()),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField(blank=True, null=True)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField(blank=True, null=True)),
                ('lokasi', models.CharField(max_length=255)),
                ('google_maps', models.URLField(blank=True)),
                ('dress_code', models.CharField(blank=True, max_length=200)),
                ('rute_color_run', models.TextField(blank=True)),
                ('fasilitas', models.TextField(blank=True, help_text='Tuliskan satu fasilitas pada setiap baris.')),
                ('hadiah_doorprize', models.TextField(blank=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('nomor_contact_person', models.CharField(max_length=20)),
                ('faq', models.TextField(blank=True, help_text='Tuliskan pertanyaan dan jawaban yang sering diajukan.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('dipublikasikan', 'Dipublikasikan'), ('berlangsung', 'Berlangsung'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='draft', max_length=20)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Event',
                'ordering': ['-tanggal_mulai', '-jam_mulai'],
            },
        ),
        migrations.CreateModel(
            name='LogAktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_aktivitas', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('tambah', 'Tambah Data'), ('ubah', 'Ubah Data'), ('hapus', 'Hapus Data'), ('verifikasi', 'Verifikasi'), ('check_in', 'Check-in'), ('reset_password', 'Reset Password'), ('backup', 'Backup Database'), ('restore', 'Restore Database'), ('lainnya', 'Lainnya')], default='lainnya', max_length=30)),
                ('deskripsi', models.TextField()),
                ('nama_tabel', models.CharField(blank=True, max_length=100)),
                ('id_objek', models.CharField(blank=True, max_length=100)),
                ('alamat_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_aktivitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Aktivitas',
                'verbose_name_plural': 'Log Aktivitas',
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='PengaturanSistem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_aplikasi', models.CharField(default='ColorRun Vest', max_length=150)),
                ('nama_penyelenggara', models.CharField(blank=True, max_length=150)),
                ('logo_event', models.ImageField(blank=True, null=True, upload_to='pengaturan/logo/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='pengaturan/banner/')),
                ('nama_bank', models.CharField(blank=True, max_length=100)),
                ('nomor_rekening', models.CharField(blank=True, max_length=50)),
                ('atas_nama_rekening', models.CharField(blank=True, max_length=150)),
                ('qris', models.ImageField(blank=True, null=True, upload_to='pengaturan/qris/')),
                ('email_admin', models.EmailField(blank=True, max_length=254)),
                ('nomor_whatsapp', models.CharField(blank=True, max_length=20)),
                ('instagram', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('alamat', models.TextField(blank=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('diperbarui_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pengaturan_diperbarui', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengaturan Sistem',
                'verbose_name_plural': 'Pengaturan Sistem',
            },
        ),
        migrations.CreateModel(
            name='KategoriTiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('kuota', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('tanggal_penjualan_mulai', models.DateTimeField(default=django.utils.timezone.now)),
                ('tanggal_penjualan_selesai', models.DateTimeField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategori_tiket', to='administrator.event')),
            ],
            options={
                'verbose_name': 'Kategori Tiket',
                'verbose_name_plural': 'Kategori Tiket',
                'ordering': ['event', 'harga'],
                'constraints': [models.UniqueConstraint(fields=('event', 'nama_kategori'), name='kategori_tiket_unik_per_event')],
            },
        ),
    ]
