# Generated by Django 5.2.16 on 2026-07-25 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='faq',
        ),
        migrations.RemoveField(
            model_name='event',
            name='google_maps',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hadiah_doorprize',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tanggal_selesai',
        ),
    ]
